<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260528120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add user_preference table for per-user UI and filter settings';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE user_preference (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, "key" VARCHAR(100) NOT NULL, value VARCHAR(500) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX user_preference_user_key ON user_preference (user_id, "key")');
        $this->addSql('ALTER TABLE user_preference ADD CONSTRAINT FK_8A293DCC76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE user_preference DROP CONSTRAINT FK_8A293DCC76ED395');
        $this->addSql('DROP TABLE user_preference');
    }
}
